# Generated by Django 6.0.2 on 2026-09-14 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System Alert'), ('REQUEST_RECEIVED', 'Request Received'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKED_UP', 'Donation Picked Up'), ('DELIVERED', 'Donation Delivered'), ('COMPLETED', 'Donation Completed'), ('ACCOUNT_VERIFIED', 'Account Verified')], default='SYSTEM', max_length=50)),
                ('link', models.CharField(blank=True, help_text='Relative URL to navigate upon clicking the notification', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
