# Generated by Django 6.0.2 on 2026-09-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Donor', 'Donor'), ('NGO', 'NGO'), ('Volunteer', 'Volunteer')], default='Donor', max_length=20),
        ),
    ]
