# Generated by Django 6.0.2 on 2026-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Donors are auto-verified; NGOs require admin verification.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Donor', 'Donor'), ('NGO', 'NGO'), ('Admin', 'Admin')], default='Donor', max_length=20),
        ),
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
    ]
