# Generated by Django 6.0.2 on 2026-09-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_is_verified_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('NGO', 'NGO')], default='DONOR', max_length=20),
        ),
    ]
