# Generated by Django 6.0.2 on 2026-09-14 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class name, e.g. bi-egg-fried, bi-book', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation Category',
                'verbose_name_plural': 'Donation Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.CharField(help_text='e.g., 50 cooked meal boxes, 2 bags of clothes, 10 books', max_length=100)),
                ('pickup_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pickup_landmark', models.CharField(blank=True, max_length=200)),
                ('preferred_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.category')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Donation Status History',
                'verbose_name_plural': 'Donation Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('Cooked Meals', 'Cooked Meals'), ('Raw Groceries', 'Raw Groceries'), ('Packaged Food', 'Packaged Food')], default='Cooked Meals', max_length=50)),
                ('preparation_time', models.DateTimeField(blank=True, help_text='When the food was cooked or packed', null=True)),
                ('expiry_time', models.DateTimeField(help_text='Safe consumption deadline')),
                ('storage_instructions', models.CharField(blank=True, help_text='e.g., Keep refrigerated, Consume within 3 hours', max_length=255)),
                ('dietary_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegan', 'Vegan')], default='Vegetarian', max_length=30)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_detail', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Food Detail',
                'verbose_name_plural': 'Food Details',
            },
        ),
    ]
