# Generated by Django 6.0.2 on 2026-09-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='DonationCategory',
        ),
        migrations.AlterModelOptions(
            name='donationcategory',
            options={'ordering': ['name'], 'verbose_name': 'Donation Category', 'verbose_name_plural': 'Donation Categories'},
        ),
        migrations.RemoveField(
            model_name='donationcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='donationcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='donationcategory',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='donationcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='fooddetail',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pickup_landmark',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='preferred_pickup_time',
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('COLLECTED', 'Collected'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=25),
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationcategory'),
        ),
        migrations.DeleteModel(
            name='DonationStatusHistory',
        ),
        migrations.DeleteModel(
            name='FoodDetail',
        ),
    ]
