# Generated by Django 6.0.2 on 2026-09-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationcategory_remove_fooddetail_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='delivery_option',
            field=models.CharField(choices=[('NGO_PICKUP', 'NGO/organization will pick up'), ('DONOR_DELIVERY', 'Donor will deliver/drop off')], default='NGO_PICKUP', help_text='Transfer method: Donor drop-off vs NGO pickup', max_length=25),
        ),
        migrations.AddField(
            model_name='donation',
            name='dropoff_location',
            field=models.CharField(blank=True, help_text='Designated drop-off point, e.g. NGO center or community partner hub', max_length=255),
        ),
    ]
