# Generated by Django 6.0.2 on 2026-09-14 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Explain how your NGO plans to distribute this donation and who will benefit.')),
                ('beneficiaries_count', models.PositiveIntegerField(default=1, help_text='Estimated number of beneficiaries')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved by Donor'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by NGO')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('donor_notes', models.TextField(blank=True, help_text='Optional remarks from the donor when accepting or rejecting the request.')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.donation')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Request',
                'verbose_name_plural': 'Donation Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned / Awaiting Pickup Schedule'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKED_UP', 'Picked Up from Donor'), ('DELIVERED', 'Delivered to NGO'), ('COMPLETED', 'Completed & Confirmed')], default='ASSIGNED', max_length=30)),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_proof_image', models.ImageField(blank=True, help_text='Photo proof of handover to NGO', null=True, upload_to='delivery_proofs/')),
                ('delivery_notes', models.TextField(blank=True, help_text='Handover observations or recipient comments')),
                ('recipient_confirmation_name', models.CharField(blank=True, help_text='Name of NGO staff member who received the items', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='donations.donation')),
                ('volunteer', models.ForeignKey(blank=True, help_text='Assigned volunteer driver/courier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_deliveries', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='donation_requests.donationrequest')),
            ],
            options={
                'verbose_name': 'Delivery Assignment',
                'verbose_name_plural': 'Delivery Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
