# Generated by Django 6.0.2 on 2026-09-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_requests', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAssignment',
        ),
    ]
