# Generated by Django 6.0.2 on 2026-09-16 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_requests', '0002_delete_deliveryassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation Request', 'verbose_name_plural': 'Donation Requests'},
        ),
        migrations.RenameField(
            model_name='donationrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='beneficiaries_count',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='donor_notes',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='responded_at',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COLLECTED', 'Collected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25),
        ),
    ]
