# Generated by Django 6.0.2 on 2026-09-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_requests', '0003_alter_donationrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Confirmed NGO contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Confirmed NGO contact person name', max_length=150),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Confirmed NGO contact phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='pickup_notes',
            field=models.TextField(blank=True, help_text='Confirmed logistics, pickup preference, or address notes'),
        ),
    ]
